TESTS: Fix compilation flags for 32 bit support.
Include lgcc support to avoid errors like:
      undefined reference to `__umoddi3'
when buildilng for 32-bit systems

For 32bit support, mabi should be ilp32 instead of lp32.

Signed-off-by: Atish Patra <atish.patra@wdc.com>
Reviewed-by: Alistair Francis <alistair.francis@wdc.com>